### ISSUE TITLE
Improve styling for home page for desktop view

### ISSUE THREAD

**Issue by laveesh** [osditech/sua-website#32]
- [ ] Change color for **signin** button in quick upload form
- [ ] Change color to primary for all subheading like testimoial, our features etc
- [ ] remove extra top and bottom space for the quick stats tile like before this tile 
![Screenshot from 2021-11-23 00-11-16](https://user-images.githubusercontent.com/31915056/142917232-bd79cb7d-07e1-4508-9f36-95271a8961f2.png)

**Comment by Shivanshu1572** [comment]
Changed colour and Styling of Home and Desktop View

- Created a new branch "Changes"
- Changed all the subheadings from blue to orange
- Reduced the padding between the div
- Changed Study lab to Swipe up In Contact and Blog Page
- Fixed Position of Upload Form
- Fixed all the links in navbars.
